services:
  - type: web
    name: telegram-gemini-bot-polling-whisper
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
